### ISSUE TITLE
Installation Instructions

### ISSUE THREAD

**Issue by dleadbetter** [recogito/recogito-studio#1]
Using the installation instructions in the `README.md` I ran in the following:

- [x] Do we need to support authentication via SSH key **and** password? I setup the root user via SSH key, but had to go into SSH config in order to allow password authentication for the recogito user.
- [x] From the documentation, it is not immediately obvious that both DNS entries for "client.example.com" and "server.example.com" should point to the same IP.
- [x] Running `snap install docker`, I received the following error: `error: access denied (try with sudo)`
- [ ] Running `sudo bash ./install-self-hosted-docker.sh`, I received the following error:

```
Finished supabase db push.
Policies:
null
Roles:
null
Role Policies:
null
Organization Admin Group:
null
/home/recogito/recogito-studio/recogito-server/create-default-groups.js:123
  if (orgAdminProfile.data.length === 0) {
                           ^

TypeError: Cannot read properties of null (reading 'length')
    at main (/home/recogito/recogito-studio/recogito-server/create-default-groups.js:123:28)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

Node.js v18.19.1
Removing repositories
Recogito Studio Installed!
```
The installation finished successfully, but as a result (I think), I was unable to log into the client.

**Comment by jamiefolsom** [comment]
Thanks for this, Derek. We do need to get this instance fully working, and log-into-able, so let's do both of the following items, today if possible:

- [ ] @lwjameson In the README, document the solution for the above issues, and share with Derek.
- [ ] @dleadbetter on this instance, fix (or complete) the install, and create an org admin account (if that's not already done as part of the install process), so I can share the info with the users.
